---
openapi: 3.0.0
info:
  title: home-iot-api
  description: The API for the EatBacon IOT project
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/RPALLING_1/API-RBD/1.0.0
  description: SwaggerHub API Auto Mocking
paths:
  /profile:
    put:
      tags:
      - Profile
      description: Este método sirve para cambiar datos que ya existen.
      operationId: putProfile
      parameters:
      - name: SessionToken
        in: header
        description: Ese es el token necesario
        required : true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Cuerpo de la petición
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Persona'
      responses:
        "200":
          description: Operación correcta
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Persona'
        "401":
          description: Token de sesión inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "400":
          description: Algún dato es de tipo incorrecto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /classes:
    post:
      tags:
      - Classes
      description: Este método sirve para cambiar datos que ya existen.
      operationId: postClasses
      parameters:
      - name: SessionToken
        in: header
        description: Ese es el token necesario
        required : true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        description: Cuerpo de la petición
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Clases'
      responses:
        "201":
          description: Creado correctamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Clases'
        "401":
          description: Token de sesión inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        "400":
          description: Algún dato es de tipo incorrecto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /orders:
    get:
      tags:
      - Orders
      description: Obtener listado de pedidos con la información de cada pedido del usuario autenticado
      operationId: getOrders
      parameters:
      - name: SessionToken
        in: header
        description: Ese es el token necesario
        required : true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: Operación correcta
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/inline_response_200'
        "401":
          description: Token de sesión inválido
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Persona:
      required:
      - DNI
      - IdPersona
      type: object
      properties:
        IdPersona:
          type: integer
          format: int32
          readOnly: true
        DNI:
          type: string
          format: uuid
          readOnly: true
        nombre:
          type: string
        correo:
          type: string
          format: email
        pago:
          type: string
        direccion:
          type: string
        Nºtelefono:
          type: integer
    Pedidos:
      required:
      - id
      type: object
      properties:
        id:
          type: integer
          format: int32
          readOnly: true
        fecha:
          type: string
          description: fecha en la que el pedido se ha realizado
          format: date-time
        cantidad:
          type: integer
          description: numero de pedidos que se realizan
          format: int32
    Clases:
      required:
      - Id
      type: object
      properties:
        Id:
          type: integer
          format: int32
          readOnly: true
        nombre:
          type: string
          description: Nombre de la clases impartida en el gimnasio
        horarios:
          type: integer
    Productos:
      required:
      - ProductosId
      type: object
      properties:
        ProductosId:
          type: integer
          description: identificador del producto
          format: int32
          readOnly: true
        name:
          type: string
          description: nombre del producto
        color:
          type: string
          description: color del producto
        precio:
          type: integer
          description: precio del producto
          format: int32
    Categorias:
      required:
      - CategoriaId
      type: object
      properties:
        CategoriaId:
          type: integer
          description: id de la categoría
          readOnly: true
        nombre:
          type: string
          description: nombre de la categoría del producto
        imagen:
          type: string
    Error:
      type: object
      properties:
        code:
          type: string
          description: Código de error
        status:
          type: integer
          description: httpstatus
          format: int32
        type:
          type: string
          description: Tipo de error
        message:
          type: string
          description: Mensaje de error
    orders_items:
      type: object
      properties:
        name:
          type: string
        quantity:
          type: integer
        unitPrice:
          type: number
          format: float
        productId:
          type: integer
    inline_response_200:
      type: object
      properties:
        orderDate:
          type: string
          format: date-time
        items:
          type: array
          items:
            $ref: '#/components/schemas/orders_items'
